import { useState } from "react";
import { Button, Empty, Modal, Select, Space, Table, Tag, Typography, message } from "antd";
import type { TableColumnsType } from "antd";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import dayjs from "dayjs";
import { downloadDocument, generateDocument, listDocumentsForPlot } from "../../api/documents";
import { listPlots } from "../../api/plots";
import type { DocumentResponse, DocumentType } from "../../types/document";
import { getApiErrorMessage } from "../../utils/errors";

const PLOTS_QUERY_KEY = ["plots"] as const;
const documentsQueryKey = (plotId: string) => ["documents", "by-plot", plotId] as const;

const DOCUMENT_TYPE_OPTIONS: Array<{ label: string; value: DocumentType }> = [
  { label: "Allotment Letter", value: "AllotmentLetter" },
  { label: "Transfer Letter", value: "TransferLetter" },
  { label: "NOC", value: "NOC" },
  { label: "Possession Letter", value: "PossessionLetter" },
];

function documentTypeLabel(type: DocumentType): string {
  return DOCUMENT_TYPE_OPTIONS.find((option) => option.value === type)?.label ?? type;
}

export default function DocumentsListPage() {
  const queryClient = useQueryClient();
  const [selectedPlotId, setSelectedPlotId] = useState<string | undefined>(undefined);
  const [isGenerateOpen, setGenerateOpen] = useState(false);
  const [documentType, setDocumentType] = useState<DocumentType | undefined>(undefined);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const { data: plots, isLoading: isPlotsLoading } = useQuery({
    queryKey: PLOTS_QUERY_KEY,
    queryFn: listPlots,
  });

  const { data: documents, isLoading: isDocumentsLoading } = useQuery({
    queryKey: selectedPlotId ? documentsQueryKey(selectedPlotId) : ["documents", "by-plot", "none"],
    queryFn: () => listDocumentsForPlot(selectedPlotId as string),
    enabled: selectedPlotId !== undefined,
  });

  const plotOptions = (plots ?? []).map((plot) => ({
    label: `${plot.plotNumber} (${plot.status})`,
    value: plot.id,
  }));
  const selectedPlot = (plots ?? []).find((plot) => plot.id === selectedPlotId) ?? null;

  const generateMutation = useMutation({
    mutationFn: (dto: { plotId: string; documentType: DocumentType }) => generateDocument(dto),
    onSuccess: () => {
      message.success("Document generated.");
      setGenerateOpen(false);
      setDocumentType(undefined);
      if (selectedPlotId) {
        void queryClient.invalidateQueries({ queryKey: documentsQueryKey(selectedPlotId) });
      }
    },
    onError: (error) => message.error(getApiErrorMessage(error, "Failed to generate document.")),
  });

  const handleDownload = async (record: DocumentResponse) => {
    setDownloadingId(record.id);
    try {
      await downloadDocument(record.id);
    } catch (error) {
      message.error(getApiErrorMessage(error, "Failed to download document."));
    } finally {
      setDownloadingId(null);
    }
  };

  const columns: TableColumnsType<DocumentResponse> = [
    {
      title: "Type",
      dataIndex: "documentType",
      key: "documentType",
      render: (type: DocumentType) => <Tag color="blue">{documentTypeLabel(type)}</Tag>,
    },
    {
      title: "Generated At",
      dataIndex: "generatedAt",
      key: "generatedAt",
      render: (generatedAt: string) => dayjs(generatedAt).format("DD-MMM-YYYY HH:mm"),
    },
    {
      title: "Generated By",
      dataIndex: "generatedBy",
      key: "generatedBy",
    },
    {
      title: "Booking",
      dataIndex: "bookingId",
      key: "bookingId",
      render: (bookingId: string | null) => bookingId ?? "—",
    },
    {
      title: "Actions",
      key: "actions",
      render: (_, record) => (
        <Button
          size="small"
          onClick={() => handleDownload(record)}
          loading={downloadingId === record.id}
        >
          Download
        </Button>
      ),
    },
  ];

  return (
    <div>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 16,
        }}
      >
        <Typography.Title level={4} style={{ margin: 0 }}>
          Documents
        </Typography.Title>
        <Space>
          <Select
            showSearch
            allowClear
            loading={isPlotsLoading}
            placeholder="Select a plot"
            style={{ width: 260 }}
            options={plotOptions}
            value={selectedPlotId}
            onChange={setSelectedPlotId}
            filterOption={(input, option) =>
              String(option?.label ?? "")
                .toLowerCase()
                .includes(input.toLowerCase())
            }
          />
          <Button
            type="primary"
            disabled={!selectedPlotId}
            onClick={() => setGenerateOpen(true)}
          >
            Generate Document
          </Button>
        </Space>
      </div>

      {selectedPlotId ? (
        <Table<DocumentResponse>
          rowKey="id"
          loading={isDocumentsLoading}
          dataSource={documents}
          columns={columns}
        />
      ) : (
        <Empty description="Select a plot to view its generated documents" />
      )}

      <Modal
        title={selectedPlot ? `Generate Document — Plot ${selectedPlot.plotNumber}` : "Generate Document"}
        open={isGenerateOpen}
        onCancel={() => {
          setGenerateOpen(false);
          setDocumentType(undefined);
        }}
        onOk={() => {
          if (selectedPlotId && documentType) {
            generateMutation.mutate({ plotId: selectedPlotId, documentType });
          }
        }}
        okButtonProps={{ disabled: !documentType, loading: generateMutation.isPending }}
        destroyOnHidden
      >
        <Typography.Paragraph type="secondary">
          Client, Booking and price details are resolved automatically from this Plot's most recent
          Booking (or its owner Client if it has none) — only the document type needs to be chosen.
        </Typography.Paragraph>
        <Select<DocumentType>
          style={{ width: "100%" }}
          placeholder="Select document type"
          options={DOCUMENT_TYPE_OPTIONS}
          value={documentType}
          onChange={setDocumentType}
        />
      </Modal>
    </div>
  );
}
